In [1]:
import pandas as pd
import numpy as np

## Difference between groupby and pivot_table
-Groupby is useful for grouping data by one or more columns and calculating aggregate functions. Pivot tab useful fro summarizing and aggregating data in a tabular format output: The output of the groupby and pivot table is different .Groupby returns a pandas series or DataFrame with the affregated data while p returns pandas DataFrame with a tabular format. Aggregation: Group by and pivot table handle aggregation differently.Group by performs aggregation on a column or set of columns while pivot performs aggregation on theintersection of rows and columns.

In [3]:
df = pd.read_csv("C:\\Users\\srava_kv\\Downloads\\sales_dataset_2000_rows.csv")

In [4]:
df

,Order_ID,Order_Date,Region,City,Sales_Person,Gender,Product_Category,Product_Name,Quantity,Unit_Price,Discount,Payment_Mode
0,1001,2025-04-13,West,Bangalore,Arjun,Female,Furniture,Paper,5,58845,4,UPI
1,1002,2025-12-15,East,Kolkata,Arjun,Male,Electronics,Table,5,62177,7,UPI
2,1003,2025-09-28,East,Hyderabad,Amit,Male,Electronics,Table,4,59219,13,Credit Card
3,1004,2025-04-17,South,Pune,Vikram,Female,Furniture,Laptop,6,11673,13,Credit Card
4,1005,2025-03-13,West,Bangalore,Vikram,Female,Office Supplies,Chair,2,21509,11,UPI
...,...,...,...,...,...,...,...,...,...,...,...,...
1995,2996,2025-06-14,West,Kolkata,Arjun,Male,Electronics,Paper,7,47094,14,Credit Card
1996,2997,2025-11-01,South,Kolkata,Rohit,Male,Office Supplies,Laptop,5,62998,4,UPI
1997,2998,2025-04-30,West,Chennai,Anjali,Male,Furniture,Printer,4,15734,7,Cash
1998,2999,2025-02-13,West,Kolkata,Kiran,Male,Electronics,Printer,8,11065,4,Cash
1999,3000,2025-11-08,West,Delhi,Kiran,Male,Office Supplies,Pen,4,27666,1,Credit Card

Find the total quantity sold in each Region.

In [8]:
result=df.groupby("Region")["Quantity"].sum()
print(result)

Region
East     2336
North    2548
South    2520
West     2711
Name: Quantity, dtype: int64

Find the average Unit_Price for each Product_Category.

In [9]:
df.groupby("Product_Category")["Unit_Price"].mean()

Product_Category
Electronics        33114.783133
Furniture          34162.684444
Office Supplies    33880.251135
Name: Unit_Price, dtype: float64

Calculate the total sales quantity by City.

In [12]:
df.groupby("City")["Quantity"].sum()

City
Bangalore    1364
Chennai      1481
Delhi        1455
Hyderabad    1429
Kolkata      1426
Mumbai       1565
Pune         1395
Name: Quantity, dtype: int64

Find the maximum discount given in each Region.

In [13]:
df.groupby("Region")["Discount"].max()

Region
East     14
North    14
South    14
West     14
Name: Discount, dtype: int64

Find the total quantity sold by Region and Product_Category.

In [15]:
df.groupby(["Product_Category","Region"])["Quantity"].sum()

Product_Category  Region
Electronics       East       880
                  North      835
                  South      773
                  West       791
Furniture         East       649
                  North      887
                  South      870
                  West      1089
Office Supplies   East       807
                  North      826
                  South      877
                  West       831
Name: Quantity, dtype: int64

Find the average Unit_Price by Region and Payment_Mode.

In [19]:
df.groupby(["Region","Payment_Mode"])["Unit_Price"].mean()

Region  Payment_Mode
East    Cash            32503.613333
        Credit Card     32547.166667
        UPI             33400.993939
North   Cash            33268.721893
        Credit Card     35560.357143
        UPI             34909.142857
South   Cash            32148.280000
        Credit Card     29949.081081
        UPI             35640.430000
West    Cash            34538.917647
        Credit Card     34686.108571
        UPI             34135.413793
Name: Unit_Price, dtype: float64

Find the total quantity sold by Gender and Region.

In [34]:
gender_counts = df.groupby("Region")["Gender"].value_counts().reset_index(name="Count")
print(gender_counts)

  Region  Gender  Count
0   East    Male    240
1   East  Female    231
2  North  Female    266
3  North    Male    246
4  South    Male    250
5  South  Female    248
6   West  Female    282
7   West    Male    237

In [26]:
df.columns = df.columns.str.strip()

In [27]:
df.columns

Index(['Order_ID', 'Order_Date', 'Region', 'City', 'Sales_Person', 'Gender',
       'Product_Category', 'Product_Name', 'Quantity', 'Unit_Price',
       'Discount', 'Payment_Mode'],
      dtype='object')

Find the minimum and maximum Unit_Price for each Product_Category using aggregation.

In [32]:
df.groupby("Product_Category")["Unit_Price"].agg(["min","max"])

                  min    max
Product_Category
Electronics       120  69492
Furniture         105  69769
Office Supplies   164  69906

Find the total and average quantity sold by each Sales_Person using aggregation.

In [39]:
result=df.groupby("Sales_Person")["Quantity"].agg(Total_Quantity="sum",Total_average="mean")
result

              Total_Quantity  Total_average
Sales_Person
Amit                     763       4.652439
Anjali                   861       5.186747
Arjun                    797       5.012579
Divya                    932       4.854167
Kiran                    732       5.191489
Meera                    821       4.916168
Priya                    891       5.500000
Rahul                    979       5.235294
Ravi                     793       4.806061
Rohit                    928       5.395349
Sneha                    776       4.760736
Vikram                   842       5.197531

Find the minimum, maximum, and average discount for each Region using aggregation

In [40]:
df.groupby("Region")["Discount"].agg(The_minimum="min",The_Maximum="max",Discount_="mean")

        The_minimum  The_Maximum  Discount_
Region
East              0           14   6.861996
North             0           14   7.052734
South             0           14   6.853414
West              0           14   6.884393

## Pivot Table

11.Create a pivot table showing total quantity by Region.

In [41]:
df.columns

Index(['Order_ID', 'Order_Date', 'Region', 'City', 'Sales_Person', 'Gender',
       'Product_Category', 'Product_Name', 'Quantity', 'Unit_Price',
       'Discount', 'Payment_Mode'],
      dtype='object')

In [44]:
df.pivot_table(values='Quantity',index="Region",aggfunc="sum")

        Quantity
Region
East        2336
North       2548
South       2520
West        2711

12.Create a pivot table showing average Unit_Price by Product_Category.

In [45]:
df.pivot_table(values="Unit_Price",index="Product_Category",aggfunc="mean")

                    Unit_Price
Product_Category
Electronics       33114.783133
Furniture         34162.684444
Office Supplies   33880.251135

13.Create a pivot table showing total quantity sold by Region and Product_Category.

In [47]:
df.pivot_table(values="Quantity",index=["Region","Product_Category"],aggfunc="sum")

                         Quantity
Region Product_Category
East   Electronics            880
       Furniture              649
       Office Supplies        807
North  Electronics            835
       Furniture              887
       Office Supplies        826
South  Electronics            773
       Furniture              870
       Office Supplies        877
West   Electronics            791
       Furniture             1089
       Office Supplies        831

14.Create a pivot table showing average discount by Payment_Mode.

In [48]:
df.pivot_table(values="Discount",index="Payment_Mode",aggfunc="mean")

              Discount
Payment_Mode
Cash          6.810642
Credit Card   7.181543
UPI           6.757143

15.Create a pivot table showing total quantity by City and Product_Category.

In [50]:
df.pivot_table(values="Quantity",index=["City","Product_Category"],aggfunc="sum")

                            Quantity
City      Product_Category
Bangalore Electronics            437
          Furniture              488
          Office Supplies        439
Chennai   Electronics            483
          Furniture              546
          Office Supplies        452
Delhi     Electronics            464
          Furniture              443
          Office Supplies        548
Hyderabad Electronics            507
          Furniture              517
          Office Supplies        405
Kolkata   Electronics            456
          Furniture              510
          Office Supplies        460
Mumbai    Electronics            498
          Furniture              494
          Office Supplies        573
Pune      Electronics            434
          Furniture              497
          Office Supplies        464

16.Create a pivot table showing average Unit_Price by Region and Gender.

In [51]:
df.pivot_table(values="Unit_Price",index=["Region","Gender"],aggfunc="mean")

                 Unit_Price
Region Gender
East   Female  33322.264069
       Male    32360.920833
North  Female  32890.657895
       Male    36446.569106
South  Female  32693.951613
       Male    33098.768000
West   Female  35234.659574
       Male    33523.514768

17.Create a pivot table showing total quantity sold by Sales_Person and Region.

In [54]:
df.pivot_table(values="Quantity",index=["Sales_Person","Region"],aggfunc="sum")

                     Quantity
Sales_Person Region
Amit         East         153
             North        197
             South        237
             West         176
Anjali       East         256
             North        206
             South        205
             West         194
Arjun        East         223
             North        131
             South        207
             West         236
Divya        East         232
             North        268
             South        212
             West         220
Kiran        East         141
             North        161
             South        196
             West         234
Meera        East         144
             North        267
             South        167
             West         243
Priya        East         247
             North        220
             South        205
             West         219
Rahul        East         182
             North        266
             South        234
             West         297
Ravi         East         188
             North        188
             South        233
             West         184
Rohit        East         190
             North        238
             South        238
             West         262
Sneha        East         192
             North        224
             South        180
             West         180
Vikram       East         188
             North        182
             South        206
             West         266

18.Create a pivot table showing average discount by Product_Category and Region.

In [55]:
df.pivot_table(values="Discount",index=["Product_Category","Region"],aggfunc="mean")

                         Discount
Product_Category Region
Electronics      East    7.011364
                 North   7.228571
                 South   6.616352
                 West    6.824675
Furniture        East    6.968992
                 North   6.942197
                 South   7.229412
                 West    6.748768
Office Supplies  East    6.620482
                 North   6.981707
                 South   6.698225
                 West    7.111111

19.Create a pivot table showing total quantity by Payment_Mode and Product_Category.

In [57]:
df.pivot_table(values="Quantity",index=["Payment_Mode","Product_Category"],aggfunc="sum")

                               Quantity
Payment_Mode Product_Category
Cash         Electronics           1070
             Furniture             1066
             Office Supplies       1042
Credit Card  Electronics           1034
             Furniture             1256
             Office Supplies       1081
UPI          Electronics           1175
             Furniture             1173
             Office Supplies       1218

20.Create a pivot table showing average quantity sold by Region, Product_Category, and Payment_Mode.

In [58]:
df.pivot_table(values="Quantity",index=["Region","Product_Category","Payment_Mode"],aggfunc="mean")

                                      Quantity
Region Product_Category Payment_Mode
East   Electronics      Cash          5.129032
                        Credit Card   4.648148
                        UPI           5.183333
       Furniture        Cash          4.810811
                        Credit Card   5.460000
                        UPI           4.714286
       Office Supplies  Cash          5.078431
                        Credit Card   4.807692
                        UPI           4.730159
North  Electronics      Cash          4.606557
                        Credit Card   4.903226
                        UPI           4.807692
       Furniture        Cash          4.941176
                        Credit Card   5.276923
                        UPI           5.122807
       Office Supplies  Cash          5.105263
                        Credit Card   4.963636
                        UPI           5.038462
South  Electronics      Cash          4.632653
                        Credit Card   4.950000
                        UPI           4.971429
       Furniture        Cash          4.777778
                        Credit Card   5.220000
                        UPI           5.318182
       Office Supplies  Cash          5.531915
                        Credit Card   4.913793
                        UPI           5.187500
West   Electronics      Cash          4.784314
                        Credit Card   5.301887
                        UPI           5.320000
       Furniture        Cash          5.178082
                        Credit Card   5.573529
                        UPI           5.354839
       Office Supplies  Cash          5.043478
                        Credit Card   5.055556
                        UPI           5.258065